### ISSUE TITLE
Создать бд, реализовать отображение чатов и сообщений из неё

### ISSUE THREAD

**Issue by NekrodNIK** [MoreliaTalk/morelia_client_qt#6]

**Comment by rus-ai** [comment]
Может БД клиента сразу делать с прицелом как модуль? Если потом потребуется в других Py-клиентах выделим в отдельную репозиторию и отправим в репу pip?

**Comment by NekrodNIK** [comment]
Возможно, главное не наплодить лишних абстракций. А так, да делай в виде модуля
